#==========================================================
#= Articoli Web Service - Versione Base
#==========================================================
server:
  port: 5051
  
spring:
  application:
    name: ArticoliWebService
#==========================================================
#= PARAMETRI DBMS POSTGRESQL 
#==========================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: 123_Stella
    url: jdbc:postgresql://localhost:5433/alphashop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

